### PR TITLE
Yeld frontend v0.0.2 -> Redesign Dapp with improved aesthetics

### LINKED ISSUE #6: Redesign dapp with improved aesthetics
Here are the illustrator design files. The final design must look identical to this one.

[YELD_dapp.zip](https://github.com/merlox/yeld-frontend/files/5360956/YELD_dapp.zip)

A good member of our community made an excellent redesign of our existing dapp. Here are the captures:

YELD_dapp_home
YELD_dapp_home_open
YELD_dapp_mobile
YELD_dapp_mobile_open

We want you to implement those visual changes while keeping the design as symmetrical and clean as possible. The faster worker gets the job. Make sure to start working as soon as you can. We can't approve multiple workers yet so the first once that gets it done will be accepted and win the price.

Feel free to ask any questions. The result should be in a separate branch and it must be 100% responsive. Pay attention to the modals when users click on buttons so they also follow the same aesthetic.

### PR DESCRIPTION
**Pull request by developerfred**
fixed #6

Todo list
- [x] Modal YieldMechanics
- [x] Change Colors
- [x] StakeSimple Component
- [x]  Responsive Mobile

ScreenShot
version02

Screen Shot 2020-10-11 at 11 31 02

Mobile
Screen Shot 2020-10-11 at 11 18 36

### CODE REVIEW

**Comment by merlox** [comment]
Great, is the design complete?

**Comment by merlox** [comment]
The design looks excellent however there are a few issues that need to be taken care of:

- Make sure to change "You Retirement Stake" to "Your Retirement Yield Stake". Also align it vertically so it's in the middle.

- Remove "You optimised Yield Farm"

- Make sure there isn't a double border in the mobile design in the retirement stake blocks

- Can you send a screenshot with the "Yield Mechanics" activated to see how it looks?

**Comment by developerfred** [comment]
> There are issues that need to be taken care of:
> 
> * Make sure to change "You Retirement Stake" to "Your Retirement Yield Stake". Also align it vertically so it's in the middle.
> * Remove "You optimised Yield Farm"
> * Make sure there isn't a double border in the mobile design in the retirement stake blocks
> * The font needs to be updated to a thinner one.
> * The texts are not positioned in the right place, check the design.
> * Can you send a screenshot with the "Yield Mechanics" activated to see how it looks?

- [x] Make sure to change "You Retirement Stake" to "Your Retirement Yield Stake". Also align it vertically so it's in the middle.

- [x] Remove "You optimised Yield Farm"

- [ ] Make sure there isn't a double border in the mobile design in the retirement stake blocks

- [ ] The font needs to be updated to a thinner one.

- [ ] The texts are not positioned in the right place, check the design.

Can you send a screenshot with the "Yield Mechanics" activated to see how it looks? Yes 
Screen Shot 2020-10-11 at 13 10 14

**Comment by developerfred** [comment]
> > There are issues that need to be taken care of:
> > 
> > * Make sure to change "You Retirement Stake" to "Your Retirement Yield Stake". Also align it vertically so it's in the middle.
> > * Remove "You optimised Yield Farm"
> > * Make sure there isn't a double border in the mobile design in the retirement stake blocks
> > * The font needs to be updated to a thinner one.
> > * The texts are not positioned in the right place, check the design.
> > * Can you send a screenshot with the "Yield Mechanics" activated to see how it looks?
> 
> * [x]  Make sure to change "You Retirement Stake" to "Your Retirement Yield Stake". Also align it vertically so it's in the middle.
> * [x]  Remove "You optimised Yield Farm"
> * [ ]  Make sure there isn't a double border in the mobile design in the retirement stake blocks
> * [ ]  The font needs to be updated to a thinner one.
> * [ ]  The texts are not positioned in the right place, check the design.
> 
> Can you send a screenshot with the "Yield Mechanics" activated to see how it looks? Yes
> Screen Shot 2020-10-11 at 13 10 14

@merlox Are we going to update the text of the modal Mechanics to the text that is in the illustration art?

**Comment by developerfred** [comment]
update 
version02

**Comment by developerfred** [comment]
@merlox Only the edges are missing now, I'm investigating why it's duplicating.

**Comment by merlox** [comment]
> @merlox Only the edges are missing now, I'm investigating why it's duplicating.

great let me know when it's ready

**Comment by developerfred** [comment]
@merlox done

Screen Shot 2020-10-11 at 17 58 13

**Comment by merlox** [comment]
looks

- Change "Your Retirement Yield Stake" to "Your Retirement Stake"
- Place "Your Retirement Stake" title on top of the action boxes like in the design picture not to the side
- Extend the Retirement Yield boxes to fill the width
- Make the content have a maximum width of 1000px while keeping the header full width
- Add the "Your Optimised Yield Farm" title back on top of the stablecoin boxes
- Move the text "This project is in beta, use at your own risk" to the bottom of the page
- The stablecoin boxes must have a clearer background

**Comment by developerfred** [comment]
@merlox Fixed on 12983beab6d0ea3b60ff3b80ca20d7cfcfdf2851

Screenshot Brave Browser
localhost_3000_

ScreenShot Mobile on Brave Browser



## TodoList 
- [x] Change "Your Retirement Yield Stake" to "Your Retirement Stake"
- [x] Place "Your Retirement Stake" title on top of the action boxes like in the design picture not to the side
- [x] Extend the Retirement Yield boxes to fill the width
Make the content have a maximum width of 1000px while keeping the header full width
- [x] Add the "Your Optimised Yield Farm" title back on top of the stablecoin boxes
- [x] Move the text "This project is in beta, use at your own risk" to the bottom of the page
- [x] The stablecoin boxes must have a clearer background
- [x] The border for the boxes is barely visible
- [x] A separator line is missing between the retirement yield section and the stablecoin boxes


- [x] I'm using a 4k screen which breaks the design. Make sure the items are properly aligned. I'm also using the brave browser.

**Comment by merlox** [comment]
Good job on the changes! The warning at the bottom is perfectly placed.

However the design still doesnt look good on my end. I've done a `git pull` from your repo and branch and here's what I get:

change

- Those 2 icons are not aligned when they should be
- The DAI box has the same background color when it should have a slightly lighter background. Check the initial design

change2

- The top row and bottom row aren't aligned for me not sure why

**Comment by developerfred** [comment]
@merlox 
- [x] Those 2 icons are not aligned …
e6e8dd9
- [x] Change Summary Background
- [x] Align Components

**Comment by merlox** [comment]
Excellent now it looks better. However the elements now space out weirdly on my screen:

change3

- Make sure to zoom out to guarantee that elements stay together on larger screens

change4

**Comment by developerfred** [comment]
@merlox 4k Done and Fixed Columns space

**Comment by merlox** [comment]
Still not aligned. Change the "optimised" for "optimized":

change10

The background color in the boxes is not homogeneous:

change11

The stake modal is all messed up:

change12

Same thing with the unstake modal which also doesn't have a border on the cancel button and it's completely out of place:

change13

**Comment by developerfred** [comment]
@merlox  Can you check if everything is ok?

Screen Shot 2020-10-12 at 23 05 58

**Comment by developerfred** [comment]
- [x] Modal Buttons
Screen Shot 2020-10-13 at 00 08 53
- [x] 4K 60% width 1800px
Screen Shot 2020-10-13 at 00 20 21
[

**Comment by merlox** [comment]
hi, be sure to submit your proposal on gitcoin so I can send you the payment

**Comment by developerfred** [comment]
@merlox Ok, I just sent it, I'm waiting....

**Comment by merlox** [comment]
I'm having issues merging it. Can you rebase from master and try to create the pull request again?

**Pull request merged**
